export const currencyCodeNameMap = {
    mapData: [
        { id: 0, code: "AED", name: "UAE Dirham" },
        { id: 1, code: "ARS", name: "Argentine Peso" },
        { id: 2, code: "AUD", name: "Australian Dollar" },
        { id: 3, code: "BGN", name: "Bulgarian Lev" },
        { id: 4, code: "BRL", name: "Brazilian Real" },
        { id: 5, code: "BSD", name: "Bahamian Dollar" },
        { id: 6, code: "CAD", name: "Canadian Dollar" },
        { id: 7, code: "CHF", name: "Swiss Franc" },
        { id: 8, code: "CLP", name: "Chilean Peso" },
        { id: 9, code: "CNY", name: "Chinese Renminbi" },
        { id: 10, code: "COP", name: "Colombian Peso" },
        { id: 11, code: "CZK", name: "Czech Koruna" },
        { id: 12, code: "DKK", name: "Danish Krone" },
        { id: 13, code: "DOP", name: "Dominican Peso" },
        { id: 14, code: "EGP", name: "Egyptian Pound" },
        { id: 15, code: "EUR", name: "Euro" },
        { id: 16, code: "FJD", name: "Fiji Dollid: ar" },
        { id: 17, code: "GBP", name: "Pound Sterling" },
        { id: 18, code: "GTQ", name: "Guatemalan Quetzal" },
        { id: 19, code: "HKD", name: "Hong Kong Dollar" },
        { id: 20, code: "HRK", name: "Croatian Kuna" },
        { id: 21, code: "HUF", name: "Hungarian Forint" },
        { id: 22, code: "IDR", name: "Indonesian Rupiah" },
        { id: 23, code: "ILS", name: "Israeli New Shekel" },
        { id: 24, code: "INR", name: "Indian Rupee" },
        { id: 25, code: "ISK", name: "Icelandic Krona" },
        { id: 26, code: "JPY", name: "Japanese Yen" },
        { id: 27, code: "KRW", name: "South Korean Won" },
        { id: 28, code: "KZT", name: "Kazakhstaid: ni Tenge" },
        { id: 29, code: "MVR", name: "Maldivian Rufiyaa" },
        { id: 30, code: "MXN", name: "Mexican Peso" },
        { id: 31, code: "MYR", name: "Malaysian Ringgit" },
        { id: 32, code: "NOK", name: "Norwegian Krone" },
        { id: 33, code: "NZD", name: "New Zealand Dollar" },
        { id: 34, code: "PAB", name: "Panamanian Balboa" },
        { id: 35, code: "PEN", name: "Peruvian Sol" },
        { id: 36, code: "PHP", name: "Philippine Peso" },
        { id: 37, code: "PKR", name: "Pakistani Rupee" },
        { id: 38, code: "PLN", name: "Polish Zloty" },
        { id: 39, code: "PYG", name: "Paraguaya Guarani" },
        { id: 40, code: "RON", name: "Romanian Leu" },
        { id: 41, code: "RUB", name: "Russian Ruble" },
        { id: 42, code: "SAR", name: "Saudi Riyal" },
        { id: 43, code: "SEK", name: "Swedish Krona" },
        { id: 44, code: "SGD", name: "Singapore Dollar" },
        { id: 45, code: "THB", name: "Thai Baht" },
        { id: 46, code: "TRY", name: "Turkish Lira" },
        { id: 47, code: "TWD", name: "New Taiwan Dollar" },
        { id: 48, code: "UAH", name: "Ukrainian Hryvnia" },
        { id: 49, code: "USD", name: "United States Dollar" },
        { id: 50, code: "UYU", name: "Uruguayan Peso" },
        { id: 51, code: "ZAR", name: "South African Rand" }
    ],
}